ETL Alternative Fuel Vehicle US

In [12]:
import pandas as pd
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [13]:

#Caraga de datos, cracion de df y visualización 
Data='Alternative Fuel Vehicles US.csv'
df=pd.read_csv(Data)
df.head()

,Category,Model,Model Year,Manufacturer,Fuel,All-Electric Range,PHEV Total Range,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,...,Conventional Fuel Economy Combined,Transmission Type,Transmission Make,Engine Type,Engine Size,Engine Cylinder Count,Number of Passengers,Heavy-Duty Power System,Notes,Drivetrain
0,Sedan/Wagon,NSX,2022.0,Acura,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,...,21.0,Auto,NaN,SI,3.5L,6.0,NaN,NaN,NaN,AWD
1,Sedan/Wagon,A3,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,...,32.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,FWD
2,Sedan/Wagon,A3 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,...,31.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
3,Sedan/Wagon,A4 allroad quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,...,26.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
4,Sedan/Wagon,A4 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,...,29.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD

In [14]:
df=df.drop_duplicates()

In [15]:
df = df.fillna(0)

In [16]:
df.columns

Index(['Category', 'Model', 'Model Year', 'Manufacturer', 'Fuel',
       'All-Electric Range', 'PHEV Total Range',
       'Alternative Fuel Economy City', 'Alternative Fuel Economy Highway',
       'Alternative Fuel Economy Combined', 'Conventional Fuel Economy City',
       'Conventional Fuel Economy Highway',
       'Conventional Fuel Economy Combined', 'Transmission Type',
       'Transmission Make', 'Engine Type', 'Engine Size',
       'Engine Cylinder Count', 'Number of Passengers',
       'Heavy-Duty Power System', 'Notes', 'Drivetrain'],
      dtype='object')

In [17]:
elim=['Transmission Make','Engine Size','Engine Type','Engine Cylinder Count','Heavy-Duty Power System','Drivetrain','Notes']

In [18]:
df=df.drop(elim,axis=1)

In [19]:
df.head()

,Category,Model,Model Year,Manufacturer,Fuel,All-Electric Range,PHEV Total Range,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Transmission Type,Number of Passengers
0,Sedan/Wagon,NSX,2022.0,Acura,Hybrid Electric,0.0,0.0,0.0,0.0,0.0,21.0,22.0,21.0,Auto,0
1,Sedan/Wagon,A3,2022.0,Audi,Hybrid Electric,0.0,0.0,0.0,0.0,0.0,29.0,38.0,32.0,Auto,0
2,Sedan/Wagon,A3 quattro,2022.0,Audi,Hybrid Electric,0.0,0.0,0.0,0.0,0.0,28.0,36.0,31.0,Auto,0
3,Sedan/Wagon,A4 allroad quattro,2022.0,Audi,Hybrid Electric,0.0,0.0,0.0,0.0,0.0,24.0,30.0,26.0,Auto,0
4,Sedan/Wagon,A4 quattro,2022.0,Audi,Hybrid Electric,0.0,0.0,0.0,0.0,0.0,26.0,34.0,29.0,Auto,0

In [21]:
df.to_csv('Fuel Vehicles Us CLean',index=False)